// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

#define CHIP_ID_ADDR 0x0000
#define CHIP_ID_PARTID GENMASK(15, 8)
#define CHIP_ID_REVID GENMASK(7, 0)
#define CHIP_ID_PARTID_SGTL5000 0xA0

#define CHIP_DIG_POWER 0x0002
#define CHIP_DIG_POWER_ADC_POWERUP BIT(6)
#define CHIP_DIG_POWER_DAC_POWERUP BIT(5)
#define CHIP_DIG_POWER_DAP_POWERUP BIT(4)
#define CHIP_DIG_POWER_I2S_OUT_POWERUP BIT(1)
#define CHIP_DIG_POWER_I2S_IN_POWERUP BIT(0)

#define CHIP_CLK_CTRL 0x0004
#define CHIP_CLK_CTRL_RATE_MODE GENMASK(5, 4)
#define CHIP_CLK_CTRL_RATE_MODE_DIV_1 0x0
#define CHIP_CLK_CTRL_RATE_MODE_DIV_2 0x1
#define CHIP_CLK_CTRL_RATE_MODE_DIV_4 0x2
#define CHIP_CLK_CTRL_RATE_MODE_DIV_6 0x3
#define CHIP_CLK_CTRL_SYS_FS GENMASK(3, 2)
#define CHIP_CLK_CTRL_SYS_FS_32_KHZ 0x0
#define CHIP_CLK_CTRL_SYS_FS_44_1_KHZ 0x1
#define CHIP_CLK_CTRL_SYS_FS_48_KHZ 0x2
#define CHIP_CLK_CTRL_SYS_FS_96_KHZ 0x3
#define CHIP_CLK_CTRL_MCLK_FREQ GENMASK(1, 0)
#define CHIP_CLK_CTRL_MCLK_FREQ_256_FS 0x0
#define CHIP_CLK_CTRL_MCLK_FREQ_384_FS 0x1
#define CHIP_CLK_CTRL_MCLK_FREQ_512_FS 0x2
#define CHIP_CLK_CTRL_MCLK_FREQ_USE_PLL 0x3

#define CHIP_I2S_CTRL 0x0006
#define CHIP_I2S_CTRL_SCLKFREQ BIT(8)
#define CHIP_I2S_CTRL_MS BIT(7)
#define CHIP_I2S_CTRL_SCLK_INV BIT(6)
#define CHIP_I2S_CTRL_DLEN GENMASK(5, 4)
#define CHIP_I2S_CTRL_DLEN_32 0x0
#define CHIP_I2S_CTRL_DLEN_24 0x1
#define CHIP_I2S_CTRL_DLEN_20 0x2
#define CHIP_I2S_CTRL_DLEN_16 0x3
#define CHIP_I2S_CTRL_I2S_MODE GENMASK(3, 2)
#define CHIP_I2S_CTRL_I2S_MODE_I2S_LEFT_JUSTIFIED 0x0
#define CHIP_I2S_CTRL_I2S_MODE_RIGHT_JUSTIFIED 0x1
#define CHIP_I2S_CTRL_I2S_MODE_PCM 0x2
#define CHIP_I2S_CTRL_LRALIGN BIT(1)
#define CHIP_I2S_CTRL_LRPOL BIT(0)

#define CHIP_SSS_CTRL 0x000A
#define CHIP_SSS_CTRL_DAP_MIX_LRSWAP BIT(14)
#define CHIP_SSS_CTRL_DAP_LRSWAP BIT(13)
#define CHIP_SSS_CTRL_DAC_LRSWAP BIT(12)
#define CHIP_SSS_CTRL_I2S_LRSWAP BIT(10)
#define CHIP_SSS_CTRL_DAP_MIX_SELECT GENMASK(9, 8)
#define CHIP_SSS_CTRL_DAP_MIX_SELECT_ADC 0x0
#define CHIP_SSS_CTRL_DAP_MIX_SELECT_I2S_IN 0x1
#define CHIP_SSS_CTRL_DAP_SELECT GENMASK(7, 6)
#define CHIP_SSS_CTRL_DAP_SELECT_ADC 0x0
#define CHIP_SSS_CTRL_DAP_SELECT_I2S_IN 0x1
#define CHIP_SSS_CTRL_DAC_SELECT GENMASK(5, 4)
#define CHIP_SSS_CTRL_DAC_SELECT_ADC 0x0
#define CHIP_SSS_CTRL_DAC_SELECT_I2S_IN 0x1
#define CHIP_SSS_CTRL_DAC_SELECT_DAP 0x3
#define CHIP_SSS_CTRL_I2S_SELECT GENMASK(1, 0)
#define CHIP_SSS_CTRL_I2S_SELECT_ADC 0x0
#define CHIP_SSS_CTRL_I2S_SELECT_I2S_IN 0x1
#define CHIP_SSS_CTRL_I2S_SELECT_DAP 0x3

#define CHIP_ADCDAC_CTRL 0x000E
#define CHIP_ADCDAC_CTRL_VOL_BUSY_DAC_RIGHT BIT(13)
#define CHIP_ADCDAC_CTRL_VOL_BUSY_DAC_LEFT BIT(12)
#define CHIP_ADCDAC_CTRL_VOL_RAMP_EN BIT(9)
#define CHIP_ADCDAC_CTRL_VOL_EXPO_RAMP BIT(8)
#define CHIP_ADCDAC_CTRL_DAC_MUTE_RIGHT BIT(3)
#define CHIP_ADCDAC_CTRL_DAC_MUTE_LEFT BIT(2)
#define CHIP_ADCDAC_CTRL_ADC_HPF_FREEZE BIT(1)
#define CHIP_ADCDAC_CTRL_ADC_HPF_BYPASS BIT(0)

#define CHIP_DAC_VOL 0x0010
#define CHIP_DAC_VOL_RIGHT GENMASK(15, 8)
#define CHIP_DAC_VOL_LEFT GENMASK(7, 0)

#define CHIP_PAD_STRENGTH 0x0014
#define CHIP_PAD_STRENGTH_I2S_LRCLK GENMASK(9, 8)
#define CHIP_PAD_STRENGTH_I2S_SCLK GENMASK(7, 6)
#define CHIP_PAD_STRENGTH_I2S_DOUT GENMASK(5, 4)
#define CHIP_PAD_STRENGTH_CTRL_DATA GENMASK(3, 2)
#define CHIP_PAD_STRENGTH_CTRL_CLK GENMASK(1, 0)

#define CHIP_ANA_ADC_CTRL 0x0020
#define CHIP_ANA_ADC_CTRL_ADC_VOL_M6DB BIT(8)
#define CHIP_ANA_ADC_CTRL_ADC_VOL_RIGHT GENMASK(7, 4)
#define CHIP_ANA_ADC_CTRL_ADC_VOL_LEFT GENMASK(3, 0)

#define CHIP_ANA_HP_CTRL 0x0022
#define CHIP_ANA_HP_CTRL_HP_VOL_RIGHT GENMASK(14, 8)
#define CHIP_ANA_HP_CTRL_HP_VOL_LEFT GENMASK(6, 0)

#define CHIP_ANA_CTRL 0x0024
#define CHIP_ANA_CTRL_MUTE_LO BIT(8)
#define CHIP_ANA_CTRL_SELECT_HP BIT(6)
#define CHIP_ANA_CTRL_EN_ZCD_HP BIT(5)
#define CHIP_ANA_CTRL_MUTE_HP BIT(4)
#define CHIP_ANA_CTRL_SELECT_ADC BIT(2)
#define CHIP_ANA_CTRL_EN_ZCD_ADC BIT(1)
#define CHIP_ANA_CTRL_MUTE_ADC BIT(0)

#define CHIP_LINREG_CTRL 0x0026
#define CHIP_LINREG_CTRL_VDDC_MAN_ASSN BIT(6)
#define CHIP_LINREG_CTRL_VDDC_ASSN_OVRD BIT(5)
#define CHIP_LINREG_CTRL_D_PROGRAMMING GENMASK(3, 0)

#define CHIP_REF_CTRL 0x0028
#define CHIP_REF_CTRL_VAG_VAL GENMASK(8, 4)
#define CHIP_REF_CTRL_BIAS_CTRL GENMASK(3, 1)
#define CHIP_REF_CTRL_SMALL_POP BIT(0)

#define CHIP_MIC_CTRL 0x002A
#define CHIP_MIC_CTRL_BIAS_RESISTOR GENMASK(9, 8)
#define CHIP_MIC_CTRL_BIAS_RESISTOR_OFF 0x0
#define CHIP_MIC_CTRL_BIAS_RESISTOR_2K 0x1
#define CHIP_MIC_CTRL_BIAS_RESISTOR_4K 0x2
#define CHIP_MIC_CTRL_BIAS_RESISTOR_8K 0x3
#define CHIP_MIC_CTRL_BIAS_VOLT GENMASK(6, 4)
#define CHIP_MIC_CTRL_GAIN GENMASK(1, 0)
#define CHIP_MIC_CTRL_GAIN_0DB 0x0
#define CHIP_MIC_CTRL_GAIN_20DB 0x1
#define CHIP_MIC_CTRL_GAIN_30DB 0x2
#define CHIP_MIC_CTRL_GAIN_40DB 0x3

#define CHIP_LINE_OUT_CTRL 0x002C
#define CHIP_LINE_OUT_CTRL_OUT_CURRENT GENMASK(11, 8)
#define CHIP_LINE_OUT_CTRL_LO_VAGCNTRL GENMASK(5, 0)

#define CHIP_LINE_OUT_VOL 0x002E
#define CHIP_LINE_OUT_CTRL_LO_VOL_RIGHT GENMASK(12, 8)
#define CHIP_LINE_OUT_CTRL_LO_VOL_LEFT GENMASK(4, 0)

#define CHIP_ANA_POWER 0x0030
#define CHIP_ANA_POWER_DAC_MONO BIT(14)
#define CHIP_ANA_POWER_LINREG_SIMPLE_POWERUP BIT(13)
#define CHIP_ANA_POWER_STARTUP_POWERUP BIT(12)
#define CHIP_ANA_POWER_VDDC_CHRGPMP_POWERUP BIT(11)
#define CHIP_ANA_POWER_PLL_POWERUP BIT(10)
#define CHIP_ANA_POWER_LINREG_D_POWERUP BIT(9)
#define CHIP_ANA_POWER_VCOAMP_POWERUP BIT(8)
#define CHIP_ANA_POWER_VAG_POWERUP BIT(7)
#define CHIP_ANA_POWER_ADC_MONO BIT(6)
#define CHIP_ANA_POWER_REFTOP_POWERUP BIT(5)
#define CHIP_ANA_POWER_HEADPHONE_POWERUP BIT(4)
#define CHIP_ANA_POWER_DAC_POWERUP BIT(3)
#define CHIP_ANA_POWER_CAPLESS_HEADPHONE_POWERUP BIT(2)
#define CHIP_ANA_POWER_ADC_POWERUP BIT(1)
#define CHIP_ANA_POWER_LINEOUT_POWERUP BIT(0)

#define CHIP_PLL_CTRL 0x0032
#define CHIP_PLL_CTRL_INT_DIVISOR GENMASK(15, 11)
#define CHIP_PLL_CTRL_FRAC_DIVISOR GENMASK(10, 0)

#define CHIP_CLK_TOP_CTRL 0x0034
#define CHIP_CLK_TOP_CTRL_ENABLE_INT_OSC BIT(11)
#define CHIP_CLK_TOP_CTRL_INPUT_FREQ_DIV2 BIT(3)

#define CHIP_ANA_STATUS 0x0036
#define CHIP_ANA_STATUS_LRSHORT_STS BIT(9)
#define CHIP_ANA_STATUS_CSHORT_STS BIT(8)
#define CHIP_ANA_STATUS_PLL_IS_LOCKED BIT(4)

#define CHIP_SHORT_CTRL 0x003C
#define CHIP_SHORT_CTRL_LVLADJR GENMASK(14, 12)
#define CHIP_SHORT_CTRL_LVLADJL GENMASK(10, 8)
#define CHIP_SHORT_CTRL_LVLADJC GENMASK(6, 4)
#define CHIP_SHORT_CTRL_MODE_LR GENMASK(3, 2)
#define CHIP_SHORT_CTRL_MODE_CM GENMASK(1, 0)

#define DAP_CONTROL 0x0100
#define DAP_CONTROL_MIX_EN BIT(4)
#define DAP_CONTROL_DAP_EN BIT(0)

#define DAP_PEQ 0x0102
#define DAP_PEQ_EN GENMASK(2, 0)