manifest:
  group-filter:
    - +babblesim
  remotes:
    - name: babblesim
      url-base: https://github.com/BabbleSim
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: lopsided98
      url-base: https://github.com/lopsided98
  projects:
    - name: zephyr
      remote: lopsided98
      revision: 15564e9340fcb4bdae970d7044f82b7bcb58418f
      import:
        name-allowlist:
          - babblesim_base
          - babblesim_ext_2G4_channel_NtNcable
          - babblesim_ext_2G4_libPhyComv1
          - babblesim_ext_2G4_modem_magic
          - babblesim_ext_2G4_phy_v1
          - bsim
          - cmsis
          - fatfs
          - hal_nordic
          - libmetal
          - net-tools
          - open-amp
          - tinycrypt
    - name: babblesim_ext_nRF_hw_models
      remote: babblesim
      repo-path: ext_nRF_hw_models.git
      path: tools/bsim/components/ext_nRF_hw_models
      revision: 9b985ea6bc237b6ae06f48eb228f2ac7f6e3b96b
    - name: west-nix
      remote: lopsided98
      revision: 2c09b5de284ab4eb3fa69da1613176e83f84dda0
      import: true
      path: tools/west-nix
  self:
    path: firmware
