manifest:
  group-filter:
    - +babblesim
  remotes:
    - name: babblesim
      url-base: https://github.com/BabbleSim
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: lopsided98
      url-base: https://github.com/lopsided98
  projects:
    - name: zephyr
      remote: lopsided98
      revision: 6bf887504555a4e5860d6d426100d696760fe9f3
      import:
        name-allowlist:
          - babblesim_base
          - babblesim_ext_2G4_channel_NtNcable
          - babblesim_ext_2G4_libPhyComv1
          - babblesim_ext_2G4_modem_magic
          - babblesim_ext_2G4_phy_v1
          - bsim
          - cmsis
          - fatfs
          - hal_nordic
          - hostap
          - libmetal
          - mbedtls
          - net-tools
          - open-amp
          - picolibc
          - tinycrypt
    - name: babblesim_ext_nRF_hw_models
      remote: babblesim
      repo-path: ext_nRF_hw_models.git
      path: tools/bsim/components/ext_nRF_hw_models
      revision: 3ede17158a9fe85c160e0384c0ad0306e24ee47e
    - name: west-nix
      remote: lopsided98
      revision: 3f31c82804e217842dc40e21ab8f95a037dfc8f7
      import: true
      path: tools/west-nix
  self:
    path: firmware
