name: "Build"
on:
  push:
  pull_request:
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get packages from flake
        id: packages
        run: |
          echo -n "packages=" >> "$GITHUB_OUTPUT"
          nix flake show --json | \
            jq -c ".packages.\"x86_64-linux\" | keys" >> "$GITHUB_OUTPUT"
    outputs:
      packages: ${{steps.packages.outputs.packages}}
  build:
    runs-on: ubuntu-latest
    needs:
      - packages
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.packages.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v2
        with:
          diagnostic-endpoint: ""
      - run: nix build .#${{ matrix.package }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package }}
          path: result
